services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # ---------------------------------------------------------
    # CMF Services
    # ---------------------------------------------------------

    # example customer save handler config
    CustomerManagementFrameworkBundle\CustomerSaveHandler\NormalizeZip:
        tags: [ cmf.customer_save_handler ]

pimcore:
    models:
        class_overrides:
            'Pimcore\Model\DataObject\Customer': 'App\Model\DataObject\Customer'


pimcore_customer_management_framework:
    customer_save_manager:
        enableAutomaticObjectNamingScheme: true

    customer_provider:
        # parent folder for active customers
        parentPath: '/Customer Management/customers'

        # parent folder for customers which are unpublished and inactive
        archiveDir: '/Customer Management/customers/_archive'

        # If a naming scheme is configured customer objects will be automatically renamend and moved to the configured folder structure as soon as the naming scheme gets applied.
        namingScheme: '{countryCode}/{zip}/{firstname}-{lastname}'

        # Parent folder for customers which are created via the "new customer" button in the customer list view
        newCustomersTempDir: '/Customer Management/customers/_temp'

    # Configuration of customer save manager
    customer_save_validator:

        # If enabled an exception will be thrown when saving a customer object if duplicate customers exist.
        checkForDuplicates: true
        requiredFields:
            # Provide valid field combinations. The customer object then is valid as soon as at least one of these field combinations is filled up.
            - [ email ]
            - [ firstname, lastname ]